// Tech Edignite - Quiz Data for all branches

export interface QuizQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number; // index of correct option
  explanation: string;
  type: "mcq" | "true-false";
  difficulty: "easy" | "medium" | "hard";
}

export interface BranchQuiz {
  branch: string;
  branchId: string;
  icon: string;
  color: string;
  description: string;
  totalQuestions: number;
  timeLimit: number; // in minutes
  questions: QuizQuestion[];
}

export const quizzes: BranchQuiz[] = [
  {
    branch: "Computer Science & Engineering",
    branchId: "CSE",
    icon: "💻",
    color: "from-blue-500 to-cyan-500",
    description: "Test your knowledge in Data Structures, Algorithms, OOP, OS, DBMS and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "What is the time complexity of binary search on a sorted array?",
        options: ["O(n)", "O(log n)", "O(n log n)", "O(1)"],
        correctAnswer: 1,
        explanation: "Binary search divides the search space in half each step, giving O(log n) time complexity.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 2,
        question: "Which data structure uses LIFO (Last In, First Out) principle?",
        options: ["Queue", "Stack", "Linked List", "Tree"],
        correctAnswer: 1,
        explanation: "A Stack follows LIFO — the last element pushed is the first one popped.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 3,
        question: "In Object-Oriented Programming, the ability of a subclass to provide its own implementation of a method defined in a parent class is called:",
        options: ["Encapsulation", "Abstraction", "Polymorphism", "Inheritance"],
        correctAnswer: 2,
        explanation: "Method overriding is a form of polymorphism where a subclass provides its own implementation of a parent class method.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 4,
        question: "Which sorting algorithm has the best average-case time complexity?",
        options: ["Bubble Sort", "Selection Sort", "Merge Sort", "Insertion Sort"],
        correctAnswer: 2,
        explanation: "Merge Sort has O(n log n) average-case complexity, which is optimal for comparison-based sorting.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 5,
        question: "A deadlock in an OS can occur even when only two processes are involved.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "Deadlock can occur with as few as two processes if each holds a resource the other needs.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 6,
        question: "What does SQL stand for?",
        options: ["Structured Query Language", "Simple Query Language", "Standard Query Logic", "Sequential Query Language"],
        correctAnswer: 0,
        explanation: "SQL stands for Structured Query Language, used to manage relational databases.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 7,
        question: "Which of the following is NOT a property of a Binary Search Tree (BST)?",
        options: [
          "Left child < Parent",
          "Right child > Parent",
          "All nodes have exactly two children",
          "In-order traversal yields sorted output",
        ],
        correctAnswer: 2,
        explanation: "BST nodes can have 0, 1, or 2 children. Not all nodes are required to have exactly two children.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 8,
        question: "The process of hiding implementation details and showing only functionality is called:",
        options: ["Polymorphism", "Encapsulation", "Abstraction", "Inheritance"],
        correctAnswer: 2,
        explanation: "Abstraction hides the internal implementation and exposes only the necessary interface.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 9,
        question: "In TCP/IP, which layer is responsible for end-to-end communication?",
        options: ["Network Layer", "Transport Layer", "Application Layer", "Data Link Layer"],
        correctAnswer: 1,
        explanation: "The Transport Layer (TCP) provides end-to-end communication, reliability, and flow control.",
        type: "mcq",
        difficulty: "hard",
      },
      {
        id: 10,
        question: "A graph with V vertices and V-1 edges that is connected and acyclic is called a tree.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "A connected, acyclic graph with V vertices has exactly V-1 edges, which is the definition of a tree.",
        type: "true-false",
        difficulty: "hard",
      },
    ],
  },
  {
    branch: "Electronics & Communication Engineering",
    branchId: "ECE",
    icon: "📡",
    color: "from-purple-500 to-pink-500",
    description: "Test your knowledge in Digital Electronics, Signal Processing, Communication Systems and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "What is the output of an AND gate when both inputs are 1?",
        options: ["0", "1", "Undefined", "Depends on power supply"],
        correctAnswer: 1,
        explanation: "An AND gate outputs 1 only when ALL inputs are 1.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 2,
        question: "According to Nyquist theorem, the minimum sampling rate must be at least:",
        options: [
          "Equal to the signal frequency",
          "Twice the highest signal frequency",
          "Half the signal frequency",
          "Four times the signal frequency",
        ],
        correctAnswer: 1,
        explanation: "The Nyquist-Shannon theorem states sampling rate must be ≥ 2× the highest frequency to avoid aliasing.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 3,
        question: "Which modulation technique is used in FM radio?",
        options: ["Amplitude Modulation", "Frequency Modulation", "Phase Modulation", "Pulse Code Modulation"],
        correctAnswer: 1,
        explanation: "FM (Frequency Modulation) radio varies the carrier wave frequency to encode audio information.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 4,
        question: "An op-amp with negative feedback acts as an amplifier with very high gain.",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation: "Negative feedback in op-amps reduces gain but improves stability, linearity, and bandwidth.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 5,
        question: "What is the decimal equivalent of binary number 1011?",
        options: ["9", "10", "11", "12"],
        correctAnswer: 2,
        explanation: "1011 in binary = 1×8 + 0×4 + 1×2 + 1×1 = 8+0+2+1 = 11 in decimal.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 6,
        question: "Which component stores energy in an electric field?",
        options: ["Inductor", "Resistor", "Capacitor", "Diode"],
        correctAnswer: 2,
        explanation: "A capacitor stores electrical energy in an electric field between its plates.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 7,
        question: "In a MOSFET, the gate terminal controls current flow by:",
        options: [
          "Direct current injection",
          "Creating an electric field to modulate channel conductivity",
          "Thermal effect",
          "Magnetic field",
        ],
        correctAnswer: 1,
        explanation: "MOSFET gate creates an electric field that modulates the conductivity of the semiconductor channel.",
        type: "mcq",
        difficulty: "hard",
      },
      {
        id: 8,
        question: "The bandwidth of an FM signal is wider than that of an equivalent AM signal.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "FM signals inherently occupy more bandwidth than AM signals carrying the same audio content.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 9,
        question: "What does VLSI stand for?",
        options: [
          "Very Large Scale Integration",
          "Variable Logic Signal Interface",
          "Virtual Layer Signal Input",
          "Very Long Sequence Instruction",
        ],
        correctAnswer: 0,
        explanation: "VLSI stands for Very Large Scale Integration, referring to ICs with millions of transistors.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 10,
        question: "Which type of filter passes signals below its cutoff frequency?",
        options: ["High-pass filter", "Band-pass filter", "Low-pass filter", "Band-stop filter"],
        correctAnswer: 2,
        explanation: "A low-pass filter allows frequencies below the cutoff frequency to pass while blocking higher frequencies.",
        type: "mcq",
        difficulty: "medium",
      },
    ],
  },
  {
    branch: "Electrical Engineering",
    branchId: "EE",
    icon: "⚡",
    color: "from-yellow-500 to-orange-500",
    description: "Test your knowledge in Power Systems, Control Systems, Electrical Machines and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "According to Ohm's Law, voltage is equal to:",
        options: ["Current × Resistance", "Current / Resistance", "Resistance / Current", "Power × Time"],
        correctAnswer: 0,
        explanation: "Ohm's Law: V = I × R, where V is voltage, I is current, and R is resistance.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 2,
        question: "Which law states that the algebraic sum of all currents at a node equals zero?",
        options: ["Ohm's Law", "Kirchhoff's Voltage Law", "Kirchhoff's Current Law", "Faraday's Law"],
        correctAnswer: 2,
        explanation: "KCL (Kirchhoff's Current Law) states that the sum of currents entering and leaving a node is zero.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 3,
        question: "A transformer can be used to change DC voltage levels.",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation: "Transformers work on the principle of electromagnetic induction and operate only with AC, not DC.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 4,
        question: "What is the unit of electrical power?",
        options: ["Volt", "Ampere", "Watt", "Ohm"],
        correctAnswer: 2,
        explanation: "Electrical power is measured in Watts (W), where P = V × I.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 5,
        question: "In a three-phase system, the voltage between two phases is called:",
        options: ["Phase voltage", "Line voltage", "Neutral voltage", "Ground voltage"],
        correctAnswer: 1,
        explanation: "Line voltage is the voltage measured between any two of the three phase conductors.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 6,
        question: "A PID controller stands for:",
        options: [
          "Proportional-Integral-Derivative",
          "Power-Input-Distribution",
          "Phase-Inversion-Delay",
          "Precision-Isolation-Detector",
        ],
        correctAnswer: 0,
        explanation: "PID stands for Proportional-Integral-Derivative, a widely used feedback control mechanism.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 7,
        question: "Power factor is defined as the ratio of:",
        options: [
          "Active power to reactive power",
          "Active power to apparent power",
          "Reactive power to apparent power",
          "Voltage to current",
        ],
        correctAnswer: 1,
        explanation: "Power factor = Active power (W) / Apparent power (VA). It ranges from 0 to 1.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 8,
        question: "Increasing the number of poles in a synchronous generator increases its synchronous speed.",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation: "Ns = 120f/P. Increasing poles (P) decreases synchronous speed, not increases it.",
        type: "true-false",
        difficulty: "hard",
      },
      {
        id: 9,
        question: "In a closed-loop control system, which element provides feedback?",
        options: ["Controller", "Plant", "Sensor/Transducer", "Actuator"],
        correctAnswer: 2,
        explanation: "Sensors or transducers measure the output and provide feedback to the controller.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 10,
        question: "What is the slip of an induction motor running at synchronous speed?",
        options: ["1", "0.5", "0", "-1"],
        correctAnswer: 2,
        explanation: "Slip = (Ns - N)/Ns. At synchronous speed, N = Ns, so slip = 0. An induction motor cannot run at Ns in practice.",
        type: "mcq",
        difficulty: "hard",
      },
    ],
  },
  {
    branch: "Mechanical Engineering",
    branchId: "ME",
    icon: "⚙️",
    color: "from-green-500 to-emerald-500",
    description: "Test your knowledge in Thermodynamics, Manufacturing, Design, Fluid Mechanics and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "Which law of thermodynamics states that energy cannot be created or destroyed?",
        options: ["Zeroth Law", "First Law", "Second Law", "Third Law"],
        correctAnswer: 1,
        explanation: "The First Law of Thermodynamics is the law of energy conservation: ΔU = Q - W.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 2,
        question: "The ideal gas law is expressed as:",
        options: ["PV = nRT", "PV = mRT", "P/V = nRT", "PV² = nRT"],
        correctAnswer: 0,
        explanation: "PV = nRT, where P=pressure, V=volume, n=moles, R=gas constant, T=temperature.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 3,
        question: "Entropy always increases in a reversible process.",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation: "In a reversible process, entropy change of the universe is zero. Entropy increases only in irreversible processes.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 4,
        question: "Which manufacturing process involves melting material and pouring it into a mold?",
        options: ["Forging", "Casting", "Extrusion", "Rolling"],
        correctAnswer: 1,
        explanation: "Casting involves pouring molten material into a mold to achieve a desired shape upon solidification.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 5,
        question: "The Carnot cycle represents the maximum possible efficiency for a heat engine between two temperature reservoirs.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "The Carnot efficiency (η = 1 - TL/TH) is the theoretical maximum for any heat engine.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 6,
        question: "What is the SI unit of stress?",
        options: ["Newton", "Pascal", "Joule", "Watt"],
        correctAnswer: 1,
        explanation: "Stress = Force/Area. The SI unit is Pascal (Pa) = N/m².",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 7,
        question: "In fluid mechanics, Bernoulli's equation relates:",
        options: [
          "Temperature, volume, and pressure",
          "Pressure, velocity, and elevation",
          "Density, viscosity, and temperature",
          "Force, mass, and acceleration",
        ],
        correctAnswer: 1,
        explanation: "Bernoulli's equation: P + ½ρv² + ρgh = constant, relating pressure, velocity, and elevation.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 8,
        question: "Young's modulus is a measure of a material's resistance to elastic deformation.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "Young's modulus (E = stress/strain) measures the stiffness/elasticity of a material.",
        type: "true-false",
        difficulty: "easy",
      },
      {
        id: 9,
        question: "Which type of gear converts rotary motion between perpendicular shafts?",
        options: ["Spur Gear", "Helical Gear", "Bevel Gear", "Rack and Pinion"],
        correctAnswer: 2,
        explanation: "Bevel gears are designed to transmit motion between shafts that are at an angle (usually 90°).",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 10,
        question: "What does CNC stand for in manufacturing?",
        options: [
          "Computer Numerical Control",
          "Computer Network Coordination",
          "Central Numeric Computation",
          "Configured Numerical Code",
        ],
        correctAnswer: 0,
        explanation: "CNC stands for Computer Numerical Control — automated machining using programmed instructions.",
        type: "mcq",
        difficulty: "easy",
      },
    ],
  },
  {
    branch: "Civil Engineering",
    branchId: "CE",
    icon: "🏗️",
    color: "from-amber-500 to-red-500",
    description: "Test your knowledge in Structural Engineering, Transportation, Geotechnical Engineering and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "Which IS code governs the design of reinforced concrete structures in India?",
        options: ["IS 800", "IS 456", "IS 875", "IS 1893"],
        correctAnswer: 1,
        explanation: "IS 456:2000 is the Indian Standard code for plain and reinforced concrete design.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 2,
        question: "The ratio of lateral strain to longitudinal strain is called:",
        options: ["Young's Modulus", "Bulk Modulus", "Poisson's Ratio", "Shear Modulus"],
        correctAnswer: 2,
        explanation: "Poisson's ratio = -lateral strain / longitudinal strain, typically between 0 and 0.5.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 3,
        question: "A simply supported beam has zero bending moment at its supports.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "At the pin and roller supports of a simply supported beam, the bending moment is zero.",
        type: "true-false",
        difficulty: "easy",
      },
      {
        id: 4,
        question: "Concrete is strong in compression but weak in:",
        options: ["Shear", "Tension", "Torsion", "Both B and C"],
        correctAnswer: 1,
        explanation: "Concrete has high compressive strength but very low tensile strength, which is why reinforcement is needed.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 5,
        question: "What is the water-cement ratio recommended for high-strength concrete?",
        options: ["0.65-0.75", "0.5-0.6", "0.3-0.45", "0.8-0.9"],
        correctAnswer: 2,
        explanation: "High-strength concrete uses a low w/c ratio (0.3-0.45) to minimize porosity and maximize strength.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 6,
        question: "Which type of foundation is suitable for soft, compressible soils?",
        options: ["Isolated Footing", "Strip Footing", "Raft/Mat Foundation", "Stepped Footing"],
        correctAnswer: 2,
        explanation: "Raft foundations spread the load over the entire building area, suitable for weak or compressible soils.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 7,
        question: "The critical path in a CPM network determines the minimum project duration.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "The critical path is the longest path in the network, determining the earliest project completion time.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 8,
        question: "What does 'OPC' stand for in cement classification?",
        options: [
          "Ordinary Portland Cement",
          "Original Portland Composite",
          "Optimized Performance Cement",
          "Oxide Portland Compound",
        ],
        correctAnswer: 0,
        explanation: "OPC stands for Ordinary Portland Cement, the most common type used in construction.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 9,
        question: "In traffic engineering, PCU stands for:",
        options: [
          "Passenger Car Unit",
          "Public Commuter Usage",
          "Peak Capacity Utilization",
          "Primary Control Unit",
        ],
        correctAnswer: 0,
        explanation: "PCU (Passenger Car Unit) is used to convert various vehicle types into equivalent car units for traffic analysis.",
        type: "mcq",
        difficulty: "hard",
      },
      {
        id: 10,
        question: "The Finite Element Method (FEM) is a numerical technique used for structural analysis.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "FEM divides structures into finite elements and solves differential equations numerically for stress/strain analysis.",
        type: "true-false",
        difficulty: "medium",
      },
    ],
  },
  {
    branch: "Chemical Engineering",
    branchId: "CHE",
    icon: "🧪",
    color: "from-teal-500 to-green-500",
    description: "Test your knowledge in Process Engineering, Reaction Kinetics, Thermodynamics and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "Which reactor type is also known as a backmix reactor?",
        options: [
          "Plug Flow Reactor (PFR)",
          "Batch Reactor",
          "Continuous Stirred Tank Reactor (CSTR)",
          "Fixed Bed Reactor",
        ],
        correctAnswer: 2,
        explanation: "CSTR is called a backmix reactor because reactants are instantly mixed with the reactor contents.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 2,
        question: "The Arrhenius equation describes the temperature dependence of the reaction rate constant.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "The Arrhenius equation k = A·e^(-Ea/RT) shows how rate constant k varies with temperature T.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 3,
        question: "Which separation process is based on differences in boiling points?",
        options: ["Extraction", "Distillation", "Filtration", "Adsorption"],
        correctAnswer: 1,
        explanation: "Distillation separates mixtures based on differences in volatility (boiling points) of components.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 4,
        question: "In the Haber process, ammonia is synthesized from:",
        options: ["Nitrogen and Hydrogen", "Nitrogen and Oxygen", "Hydrogen and Methane", "Oxygen and Methane"],
        correctAnswer: 0,
        explanation: "The Haber process: N₂ + 3H₂ ⇌ 2NH₃, producing ammonia from nitrogen and hydrogen.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 5,
        question: "What does HAZOP stand for?",
        options: [
          "Hazard and Operability Study",
          "High-pressure Analysis of Zone Operations",
          "Hazardous Area Zone Optimization",
          "Heat and Zone Operational Protocol",
        ],
        correctAnswer: 0,
        explanation: "HAZOP is a structured process hazard analysis technique to identify safety and operability issues.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 6,
        question: "Le Chatelier's Principle states that a system at equilibrium will resist changes imposed on it.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "Le Chatelier's Principle: If a system at equilibrium is disturbed, it shifts to counteract the disturbance.",
        type: "true-false",
        difficulty: "easy",
      },
      {
        id: 7,
        question: "The Reynolds number determines whether fluid flow is:",
        options: [
          "Hot or cold",
          "Laminar or turbulent",
          "Compressible or incompressible",
          "Reactive or non-reactive",
        ],
        correctAnswer: 1,
        explanation: "Re < 2100: laminar, Re > 4000: turbulent. Reynolds number predicts the flow regime.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 8,
        question: "Which software is most commonly used for process simulation in chemical engineering?",
        options: ["MATLAB", "AutoCAD", "Aspen Plus", "SolidWorks"],
        correctAnswer: 2,
        explanation: "Aspen Plus is the industry-standard chemical process simulation software widely used by chemical engineers.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 9,
        question: "A heterogeneous catalyst is in the same phase as the reactants.",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation: "In heterogeneous catalysis, the catalyst is in a different phase from the reactants (e.g., solid catalyst with gas/liquid reactants).",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 10,
        question: "In distillation, the McCabe-Thiele method is used to determine the number of:",
        options: [
          "Reactor stages",
          "Theoretical plates/stages",
          "Heat exchangers",
          "Pumping stages",
        ],
        correctAnswer: 1,
        explanation: "The McCabe-Thiele graphical method is used to determine the number of theoretical stages in a distillation column.",
        type: "mcq",
        difficulty: "hard",
      },
    ],
  },
  {
    branch: "Information Technology",
    branchId: "IT",
    icon: "🌐",
    color: "from-indigo-500 to-purple-500",
    description: "Test your knowledge in Web Development, Networking, Databases, Cybersecurity and more.",
    totalQuestions: 10,
    timeLimit: 15,
    questions: [
      {
        id: 1,
        question: "What does HTTP stand for?",
        options: [
          "HyperText Transfer Protocol",
          "High Transfer Technology Protocol",
          "HyperText Transport Procedure",
          "Host Transfer Technology Proxy",
        ],
        correctAnswer: 0,
        explanation: "HTTP (HyperText Transfer Protocol) is the foundation of data communication on the World Wide Web.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 2,
        question: "In relational databases, a primary key can contain NULL values.",
        options: ["True", "False"],
        correctAnswer: 1,
        explanation: "A primary key must be unique and NOT NULL — it uniquely identifies each record in a table.",
        type: "true-false",
        difficulty: "easy",
      },
      {
        id: 3,
        question: "Which of the following is a NoSQL database?",
        options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
        correctAnswer: 2,
        explanation: "MongoDB is a document-oriented NoSQL database, while MySQL, PostgreSQL, and Oracle are relational (SQL) databases.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 4,
        question: "In computer networking, the OSI model has how many layers?",
        options: ["4", "5", "6", "7"],
        correctAnswer: 3,
        explanation: "The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.",
        type: "mcq",
        difficulty: "easy",
      },
      {
        id: 5,
        question: "What does SSL/TLS provide in web security?",
        options: [
          "Authentication only",
          "Encryption and secure communication",
          "Network address translation",
          "Packet filtering",
        ],
        correctAnswer: 1,
        explanation: "SSL/TLS provides encryption, data integrity, and authentication for secure communications over networks.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 6,
        question: "REST API is stateless, meaning each request contains all necessary information.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "RESTful APIs are stateless — each request must contain all information needed; no session state is stored server-side.",
        type: "true-false",
        difficulty: "medium",
      },
      {
        id: 7,
        question: "Which normal form eliminates partial dependencies?",
        options: ["1NF", "2NF", "3NF", "BCNF"],
        correctAnswer: 1,
        explanation: "2NF (Second Normal Form) eliminates partial dependencies of non-key attributes on a composite primary key.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 8,
        question: "IPv6 addresses are how many bits long?",
        options: ["32", "64", "128", "256"],
        correctAnswer: 2,
        explanation: "IPv6 uses 128-bit addresses (vs IPv4's 32-bit), allowing ~3.4×10³⁸ unique addresses.",
        type: "mcq",
        difficulty: "medium",
      },
      {
        id: 9,
        question: "A SQL injection attack manipulates database queries through unsanitized user input.",
        options: ["True", "False"],
        correctAnswer: 0,
        explanation: "SQL injection is a web security vulnerability where attackers inject malicious SQL through user input fields.",
        type: "true-false",
        difficulty: "easy",
      },
      {
        id: 10,
        question: "Which cloud service model provides virtualized computing resources over the internet?",
        options: ["SaaS", "PaaS", "IaaS", "FaaS"],
        correctAnswer: 2,
        explanation: "IaaS (Infrastructure as a Service) provides virtualized computing infrastructure (servers, storage, networking) over the internet.",
        type: "mcq",
        difficulty: "hard",
      },
    ],
  },
];
