// Tech Edignite — Branch Roadmap & Flowchart Data

export interface StudyPhase {
  year: number;
  label: string;
  semesters: string;
  color: string;
  subjects: string[];
  skills: string[];
  outcome: string;
  tip: string;
}

export interface CareerPath {
  id: string;
  title: string;
  icon: string;
  color: string;
  description: string;
  steps: string[];
  avgSalary: string;
  topCompanies: string[];
}

export interface SkillNode {
  category: string;
  icon: string;
  items: string[];
  priority: "Must Learn" | "Good to Have" | "Advanced";
}

export interface BranchRoadmap {
  branchId: string;
  branch: string;
  icon: string;
  color: string;
  gradient: string;
  tagline: string;
  overview: string;
  studyPhases: StudyPhase[];
  careerPaths: CareerPath[];
  skillMap: SkillNode[];
  toolsToLearn: string[];
  topResources: { name: string; type: string }[];
}

export const roadmaps: BranchRoadmap[] = [
  // ── CSE ─────────────────────────────────────────────────────────────────────
  {
    branchId: "CSE",
    branch: "Computer Science & Engineering",
    icon: "💻",
    color: "blue",
    gradient: "from-blue-500 to-cyan-500",
    tagline: "Build the digital future — from algorithms to AI",
    overview:
      "CSE students at SVNIT learn programming, algorithms, systems, databases, and AI. The 4-year journey takes you from coding basics to industry-ready software engineering skills.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-blue-500",
        subjects: [
          "Mathematics I & II",
          "Engineering Physics",
          "Introduction to Programming (C)",
          "Engineering Drawing",
          "Communication Skills",
        ],
        skills: ["C Programming", "Basic Mathematics", "Linux CLI basics"],
        outcome: "Strong mathematical base + first programming language",
        tip: "Master C pointers and recursion early — they form the backbone of all future programs.",
      },
      {
        year: 2,
        label: "Core Concepts",
        semesters: "Sem 3 & 4",
        color: "bg-indigo-500",
        subjects: [
          "Data Structures & Algorithms",
          "Object-Oriented Programming (Java)",
          "Discrete Mathematics",
          "Digital Logic Design",
          "Computer Organization",
          "Database Management (DBMS)",
        ],
        skills: [
          "Java OOP", "DSA (Arrays, Trees, Graphs)", "SQL", "Git",
        ],
        outcome: "Core CS fundamentals — ready for internship applications",
        tip: "LeetCode + DBMS labs simultaneously. Start GitHub early.",
      },
      {
        year: 3,
        label: "Advanced Topics",
        semesters: "Sem 5 & 6",
        color: "bg-violet-500",
        subjects: [
          "Operating Systems",
          "Computer Networks",
          "Compiler Design",
          "Theory of Computation",
          "Software Engineering",
          "Machine Learning",
          "Web Development (elective)",
        ],
        skills: [
          "System Design basics", "REST APIs", "React/Node.js",
          "ML with Python", "Docker basics",
        ],
        outcome: "Full-stack capable + ML foundations",
        tip: "Do your best on internship projects — this is your portfolio year!",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-purple-500",
        subjects: [
          "Distributed Systems",
          "Cloud Computing (elective)",
          "Deep Learning (elective)",
          "Information Security",
          "B.Tech Project",
        ],
        skills: [
          "Cloud (AWS/GCP)", "System Design", "DevOps", "Data Structures (interview prep)",
        ],
        outcome: "Job-ready / GATE-ready / Research-ready",
        tip: "Focus on mock interviews and system design for tech company placements.",
      },
    ],
    careerPaths: [
      {
        id: "sde",
        title: "Software Development Engineer",
        icon: "🖥️",
        color: "bg-blue-500",
        description: "Build products at top tech companies — from startups to FAANG.",
        steps: ["Master DSA", "Learn System Design", "Build projects", "Crack campus interviews"],
        avgSalary: "₹8–40 LPA",
        topCompanies: ["Google", "Microsoft", "Amazon", "Flipkart", "PhonePe"],
      },
      {
        id: "ml",
        title: "ML / AI Engineer",
        icon: "🤖",
        color: "bg-violet-500",
        description: "Build intelligent systems using ML, Deep Learning, and NLP.",
        steps: ["Python + Math", "Scikit-learn → PyTorch", "Kaggle competitions", "Research papers"],
        avgSalary: "₹10–35 LPA",
        topCompanies: ["NVIDIA", "Adobe", "ISRO", "Startups", "Research Labs"],
      },
      {
        id: "gate",
        title: "GATE / Higher Studies",
        icon: "🎓",
        color: "bg-green-500",
        description: "Pursue M.Tech at IITs/NITs or MS/PhD abroad.",
        steps: ["GATE preparation from Year 3", "Target 95+ percentile", "Apply IITs/IISC", "MS/PhD abroad"],
        avgSalary: "₹14–25 LPA (post M.Tech)",
        topCompanies: ["IIT Bombay", "IIT Delhi", "IISC", "CMU (US)", "TU Delft"],
      },
      {
        id: "startup",
        title: "Startup / Entrepreneur",
        icon: "🚀",
        color: "bg-orange-500",
        description: "Found your own tech startup or join early-stage companies.",
        steps: ["Build side projects", "Learn full-stack", "Validate ideas", "Network at hackathons"],
        avgSalary: "₹0–∞",
        topCompanies: ["Your Own Startup", "YC Portfolio", "Sequoia-backed"],
      },
    ],
    skillMap: [
      {
        category: "Programming Languages",
        icon: "⌨️",
        priority: "Must Learn",
        items: ["C", "Java", "Python", "JavaScript/TypeScript"],
      },
      {
        category: "Web & Backend",
        icon: "🌐",
        priority: "Good to Have",
        items: ["React", "Node.js", "Spring Boot", "REST APIs", "GraphQL"],
      },
      {
        category: "Databases",
        icon: "🗄️",
        priority: "Must Learn",
        items: ["MySQL", "PostgreSQL", "MongoDB", "Redis"],
      },
      {
        category: "Cloud & DevOps",
        icon: "☁️",
        priority: "Good to Have",
        items: ["AWS", "Docker", "Kubernetes", "CI/CD", "Linux"],
      },
      {
        category: "DSA & Competitive",
        icon: "🧠",
        priority: "Must Learn",
        items: ["LeetCode 200+ problems", "Codeforces", "HackerRank", "System Design"],
      },
      {
        category: "AI / ML",
        icon: "🤖",
        priority: "Advanced",
        items: ["NumPy/Pandas", "Scikit-learn", "PyTorch", "Hugging Face", "MLOps"],
      },
    ],
    toolsToLearn: ["VS Code", "Git & GitHub", "Postman", "Docker", "Jupyter Notebook", "Linux Terminal", "Figma (basics)"],
    topResources: [
      { name: "NPTEL IIT Courses", type: "Online Course" },
      { name: "LeetCode", type: "Practice Platform" },
      { name: "CS50 (Harvard)", type: "Online Course" },
      { name: "GeeksForGeeks", type: "Reference" },
      { name: "Striver's DSA Sheet", type: "DSA Guide" },
    ],
  },

  // ── ECE ──────────────────────────────────────────────────────────────────────
  {
    branchId: "ECE",
    branch: "Electronics & Communication Engineering",
    icon: "📡",
    color: "purple",
    gradient: "from-purple-500 to-pink-500",
    tagline: "Design the signals and systems that connect the world",
    overview:
      "ECE bridges hardware and software — from VLSI chip design to wireless 5G communication. SVNIT ECE prepares you for roles in semiconductors, telecom, embedded systems, and signal processing.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-purple-400",
        subjects: [
          "Mathematics I & II",
          "Engineering Physics (Wave Optics, EM Theory)",
          "Basic Electronics",
          "Introduction to Electrical Engineering",
          "Programming in C",
        ],
        skills: ["Circuit analysis basics", "Ohm's Law", "C programming"],
        outcome: "Physics + circuit fundamentals established",
        tip: "Deeply understand Kirchhoff's laws and RC circuits — everything builds on these.",
      },
      {
        year: 2,
        label: "Core Electronics",
        semesters: "Sem 3 & 4",
        color: "bg-purple-500",
        subjects: [
          "Network Analysis",
          "Electronic Devices & Circuits",
          "Digital Electronics",
          "Signals & Systems",
          "Electromagnetic Theory",
          "Data Structures",
        ],
        skills: ["BJT/MOSFET analysis", "Logic gates", "Laplace/Fourier Transforms", "MATLAB"],
        outcome: "Ready for embedded systems and signal processing labs",
        tip: "Learn MATLAB early — you'll use it throughout ECE for simulation.",
      },
      {
        year: 3,
        label: "Communication & VLSI",
        semesters: "Sem 5 & 6",
        color: "bg-pink-500",
        subjects: [
          "Digital Signal Processing",
          "Analog & Digital Communication",
          "VLSI Design",
          "Microprocessors & Microcontrollers",
          "Control Systems",
          "Wireless Communication (elective)",
        ],
        skills: ["VHDL/Verilog", "Arduino/ESP32", "DSP algorithms", "PCB design"],
        outcome: "Can design communication systems and embedded projects",
        tip: "Build an IoT project in Sem 5 — great for resume and learning.",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-rose-500",
        subjects: [
          "RF & Microwave Engineering (elective)",
          "Advanced VLSI (elective)",
          "5G Networks (elective)",
          "Image Processing",
          "B.Tech Project",
        ],
        skills: ["Cadence/Synopsys (VLSI)", "RF simulation", "5G standards", "Signal integrity"],
        outcome: "Semiconductor / Telecom / VLSI / Core ECE industry ready",
        tip: "Intern at a semiconductor company in Year 3 — VLSI roles are highly paid.",
      },
    ],
    careerPaths: [
      {
        id: "vlsi",
        title: "VLSI / Chip Design Engineer",
        icon: "🔲",
        color: "bg-purple-500",
        description: "Design digital/analog ICs. Work with Synopsys, Cadence tools.",
        steps: ["Master Verilog/VHDL", "Logic synthesis & verification", "FPGA projects", "Cadence tools"],
        avgSalary: "₹6–25 LPA",
        topCompanies: ["Intel", "Qualcomm", "Samsung", "Texas Instruments", "Synopsys"],
      },
      {
        id: "embedded",
        title: "Embedded Systems Engineer",
        icon: "🔌",
        color: "bg-pink-500",
        description: "Program microcontrollers and build hardware-software products.",
        steps: ["C/C++ embedded", "RTOS basics", "ARM Cortex MCUs", "IoT protocols"],
        avgSalary: "₹5–18 LPA",
        topCompanies: ["Bosch", "Honeywell", "Tata Elxsi", "Wipro", "L&T"],
      },
      {
        id: "telecom",
        title: "Telecom / 5G Engineer",
        icon: "📶",
        color: "bg-blue-500",
        description: "Work on next-gen wireless networks, signal processing, and RF.",
        steps: ["Digital communications", "5G NR standards", "Python DSP", "Network simulation"],
        avgSalary: "₹5–20 LPA",
        topCompanies: ["Ericsson", "Nokia", "Jio", "Airtel", "Samsung R&D"],
      },
      {
        id: "gate-ece",
        title: "GATE / M.Tech / PSU",
        icon: "🎓",
        color: "bg-green-500",
        description: "IIT M.Tech or PSU (ISRO, DRDO, BEL, BHEL, Power Grid).",
        steps: ["GATE ECE prep from Sem 5", "Focus: Networks, Signals, EDC, EMFT", "PSU cut-offs", "IIT interviews"],
        avgSalary: "₹8–20 LPA (PSU)",
        topCompanies: ["ISRO", "DRDO", "BEL", "BHEL", "NTPC"],
      },
    ],
    skillMap: [
      { category: "HDL Languages", icon: "💾", priority: "Must Learn", items: ["Verilog", "VHDL", "SystemVerilog"] },
      { category: "Embedded Programming", icon: "🔌", priority: "Must Learn", items: ["C", "C++ (bare metal)", "Arduino", "STM32", "RTOS"] },
      { category: "Simulation Tools", icon: "🖥️", priority: "Must Learn", items: ["MATLAB/Simulink", "LTSpice", "Cadence", "ModelSim"] },
      { category: "Communication", icon: "📡", priority: "Good to Have", items: ["5G NR", "WiFi 802.11", "Bluetooth LE", "LoRa", "OFDM"] },
      { category: "PCB & Hardware", icon: "🔧", priority: "Good to Have", items: ["KiCad", "Altium", "Oscilloscope", "Spectrum Analyzer"] },
      { category: "Programming", icon: "⌨️", priority: "Good to Have", items: ["Python (DSP/ML)", "MATLAB scripts", "LabVIEW"] },
    ],
    toolsToLearn: ["MATLAB", "Cadence Virtuoso", "ModelSim", "Keil MDK", "Arduino IDE", "Proteus", "KiCad"],
    topResources: [
      { name: "NPTEL: Digital Communications", type: "Course" },
      { name: "All About Circuits", type: "Reference" },
      { name: "MIT OpenCourseWare (6.002)", type: "Course" },
      { name: "The Art of Electronics", type: "Book" },
      { name: "Razavi's Microelectronics", type: "Book" },
    ],
  },

  // ── EE ───────────────────────────────────────────────────────────────────────
  {
    branchId: "EE",
    branch: "Electrical Engineering",
    icon: "⚡",
    color: "yellow",
    gradient: "from-yellow-500 to-orange-500",
    tagline: "Power the nation — from generation to grid automation",
    overview:
      "EE at SVNIT covers power systems, electrical machines, control systems, and power electronics. Career paths range from PSU jobs (ISRO, NTPC) and renewable energy to core automation roles.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-yellow-400",
        subjects: ["Mathematics I & II", "Basic Electrical Engineering", "Engineering Physics", "Workshop Practice"],
        skills: ["Ohm's Law", "AC/DC circuits", "Basic lab equipment"],
        outcome: "Solid circuit theory foundation",
        tip: "Practice AC circuit analysis — phasors, impedance, and power factor.",
      },
      {
        year: 2,
        label: "Core Electrical",
        semesters: "Sem 3 & 4",
        color: "bg-amber-500",
        subjects: [
          "Electrical Machines I & II",
          "Electromagnetic Field Theory",
          "Network Analysis",
          "Digital Electronics",
          "Power Electronics",
        ],
        skills: ["Transformer analysis", "DC/AC machines", "MATLAB basics", "PSpice simulation"],
        outcome: "Understanding of all classical electrical machines",
        tip: "The machine equivalent circuits are key — draw them for every analysis.",
      },
      {
        year: 3,
        label: "Power Systems & Control",
        semesters: "Sem 5 & 6",
        color: "bg-orange-500",
        subjects: [
          "Power Systems I & II",
          "Control Systems",
          "High Voltage Engineering",
          "Power System Protection",
          "Renewable Energy Systems (elective)",
        ],
        skills: ["MATLAB/Simulink power models", "PID control", "Load flow analysis", "ETAP software"],
        outcome: "Understand the full power grid from generation to distribution",
        tip: "MATLAB Simulink models for power systems are industry-standard — master them.",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-red-500",
        subjects: [
          "Electric Drives",
          "Flexible AC Transmission (FACTS) (elective)",
          "Smart Grid (elective)",
          "Power System Planning",
          "B.Tech Project",
        ],
        skills: ["Smart grid tech", "EV drivetrains", "SCADA systems", "PLC programming"],
        outcome: "PSU/core industry ready + GATE ready",
        tip: "Focus on GATE preparation from Sem 5 — EE PSU jobs are gold.",
      },
    ],
    careerPaths: [
      {
        id: "psu",
        title: "PSU (Government) Engineer",
        icon: "🏛️",
        color: "bg-yellow-500",
        description: "ISRO, NTPC, BHEL, Power Grid — prestigious, stable, high-paying.",
        steps: ["GATE EE preparation", "Focus: Power Systems, Machines, Control", "PSU application", "Interview prep"],
        avgSalary: "₹8–18 LPA",
        topCompanies: ["ISRO", "NTPC", "BHEL", "Power Grid", "ONGC"],
      },
      {
        id: "renewable",
        title: "Renewable Energy Engineer",
        icon: "☀️",
        color: "bg-green-500",
        description: "Design solar, wind, and hybrid energy systems.",
        steps: ["Solar PV design", "Wind turbine systems", "Grid integration", "HOMER/PVSYST software"],
        avgSalary: "₹5–15 LPA",
        topCompanies: ["Adani Green", "ReNew Power", "Suzlon", "SECI", "Waaree"],
      },
      {
        id: "automation",
        title: "Industrial Automation Engineer",
        icon: "🏭",
        color: "bg-blue-500",
        description: "Program PLCs, SCADA, and build automated manufacturing systems.",
        steps: ["PLC programming (Siemens, Allen Bradley)", "SCADA", "Drives & motors", "Industrial protocols"],
        avgSalary: "₹4–15 LPA",
        topCompanies: ["Siemens", "ABB", "Schneider", "Rockwell", "L&T"],
      },
      {
        id: "ev",
        title: "EV & Power Electronics",
        icon: "🔋",
        color: "bg-emerald-500",
        description: "Work on EV powertrains, BMS, and power converters.",
        steps: ["Power electronics converters", "Battery management", "EV standards", "MATLAB EV modeling"],
        avgSalary: "₹6–20 LPA",
        topCompanies: ["Ola Electric", "Tata Motors", "Tesla", "BYD", "Ather"],
      },
    ],
    skillMap: [
      { category: "Power Systems", icon: "⚡", priority: "Must Learn", items: ["Load flow", "Fault analysis", "Stability", "Protection relays"] },
      { category: "Simulation Tools", icon: "🖥️", priority: "Must Learn", items: ["MATLAB/Simulink", "ETAP", "PSCAD", "PSPICE"] },
      { category: "Automation & PLC", icon: "🏭", priority: "Good to Have", items: ["Siemens TIA Portal", "Allen Bradley", "SCADA", "HMI"] },
      { category: "Renewable Energy", icon: "☀️", priority: "Good to Have", items: ["HOMER", "PVGIS", "SAM", "Solar PV design"] },
      { category: "Programming", icon: "⌨️", priority: "Good to Have", items: ["MATLAB", "Python (control)", "C (embedded)"] },
      { category: "Standards & Codes", icon: "📜", priority: "Advanced", items: ["IEC standards", "IEEE standards", "IS codes", "Grid codes"] },
    ],
    toolsToLearn: ["MATLAB/Simulink", "ETAP", "AutoCAD Electrical", "Siemens TIA Portal", "PSCAD", "HOMER"],
    topResources: [
      { name: "NPTEL: Power Systems", type: "Course" },
      { name: "Chapman: Electric Machinery", type: "Book" },
      { name: "Glover: Power Systems Analysis", type: "Book" },
      { name: "NPTEL: Control Engg", type: "Course" },
      { name: "GATE EE PYQ Analysis", type: "Practice" },
    ],
  },

  // ── ME ───────────────────────────────────────────────────────────────────────
  {
    branchId: "ME",
    branch: "Mechanical Engineering",
    icon: "⚙️",
    color: "green",
    gradient: "from-green-500 to-emerald-500",
    tagline: "Design, build, and optimize the machines of tomorrow",
    overview:
      "ME at SVNIT covers thermodynamics, manufacturing, design, and robotics. Career paths include core manufacturing, R&D, PSU jobs, and exciting roles in robotics and automotive.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-green-400",
        subjects: ["Mathematics I & II", "Engineering Physics", "Engineering Mechanics", "Workshop Practice", "Engineering Drawing"],
        skills: ["AutoCAD 2D basics", "Machine shop operations", "Free body diagrams"],
        outcome: "Core mechanics foundation + hands-on workshop skills",
        tip: "Engineering Drawing accuracy matters — practice orthographic projections daily.",
      },
      {
        year: 2,
        label: "Core Mechanical",
        semesters: "Sem 3 & 4",
        color: "bg-green-500",
        subjects: [
          "Thermodynamics",
          "Strength of Materials",
          "Manufacturing Processes",
          "Theory of Machines",
          "Fluid Mechanics",
          "Metrology",
        ],
        skills: ["SolidWorks/CATIA basics", "FBD analysis", "Circuit basics", "MATLAB"],
        outcome: "Full classical mechanical engineering foundation",
        tip: "Thermodynamics diagrams (PV, TS) — draw them for every cycle analysis.",
      },
      {
        year: 3,
        label: "Design & Advanced",
        semesters: "Sem 5 & 6",
        color: "bg-emerald-500",
        subjects: [
          "Machine Design",
          "Heat Transfer",
          "Turbo Machinery",
          "CNC & Advanced Manufacturing",
          "Robotics (elective)",
          "Finite Element Method",
        ],
        skills: ["SolidWorks advanced", "ANSYS FEA", "CNC G-code", "Robotic kinematics"],
        outcome: "Can design machine components and run FEA simulations",
        tip: "Learn ANSYS during this year — FEA is used in every core industry.",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-teal-500",
        subjects: [
          "Industrial Engineering",
          "Automobile Engineering (elective)",
          "Additive Manufacturing (elective)",
          "Industry 4.0 (elective)",
          "B.Tech Project",
        ],
        skills: ["ANSYS advanced", "3D printing", "GD&T", "ERP systems (SAP basics)"],
        outcome: "Core manufacturing / R&D / PSU / Automobile industry ready",
        tip: "3D printing knowledge is booming — explore it as your project domain.",
      },
    ],
    careerPaths: [
      {
        id: "design",
        title: "Design / R&D Engineer",
        icon: "✏️",
        color: "bg-green-500",
        description: "Design machine components, run simulations, develop new products.",
        steps: ["Master SolidWorks/CATIA", "ANSYS FEA", "GD&T & tolerances", "DFM/DFA principles"],
        avgSalary: "₹4–15 LPA",
        topCompanies: ["Tata Motors", "Mahindra", "Volvo", "GE", "Siemens"],
      },
      {
        id: "manufacturing",
        title: "Manufacturing / Production Engineer",
        icon: "🏭",
        color: "bg-blue-500",
        description: "Optimize production lines, manage quality and processes.",
        steps: ["Lean manufacturing", "Six Sigma", "CNC operations", "Quality systems (ISO)"],
        avgSalary: "₹4–12 LPA",
        topCompanies: ["Bosch", "Maruti Suzuki", "Hero MotoCorp", "L&T", "BHEL"],
      },
      {
        id: "psu-me",
        title: "PSU / Government Engineer",
        icon: "🏛️",
        color: "bg-yellow-500",
        description: "BHEL, ISRO, HAL, DRDO — prestigious core engineering roles.",
        steps: ["GATE ME preparation", "Focus: Thermodynamics, FM, SOM, Manufacturing", "PSU application", "Interview"],
        avgSalary: "₹8–18 LPA",
        topCompanies: ["ISRO", "DRDO", "HAL", "BHEL", "BEML"],
      },
      {
        id: "robotics",
        title: "Robotics / EV / Automation",
        icon: "🤖",
        color: "bg-purple-500",
        description: "Design robots, EV systems, and automated machinery.",
        steps: ["ROS basics", "Python for robotics", "Mechatronics", "EV powertrain"],
        avgSalary: "₹6–20 LPA",
        topCompanies: ["Tesla", "Amazon Robotics", "Ola Electric", "Tata Motors EV", "ABB"],
      },
    ],
    skillMap: [
      { category: "CAD/CAM Software", icon: "✏️", priority: "Must Learn", items: ["SolidWorks", "AutoCAD", "CATIA", "Fusion 360"] },
      { category: "Simulation (FEA/CFD)", icon: "🖥️", priority: "Must Learn", items: ["ANSYS Structural", "ANSYS Fluent", "OpenFOAM"] },
      { category: "Manufacturing", icon: "🏭", priority: "Must Learn", items: ["CNC Machining", "GD&T", "Lean/Six Sigma", "3D Printing"] },
      { category: "Programming", icon: "⌨️", priority: "Good to Have", items: ["MATLAB", "Python", "G-code", "Arduino (mechatronics)"] },
      { category: "Management", icon: "📊", priority: "Good to Have", items: ["Project Management", "SAP basics", "Supply Chain", "Quality (ISO 9001)"] },
      { category: "Emerging Tech", icon: "🚀", priority: "Advanced", items: ["Industry 4.0", "ROS", "EV systems", "Additive Manufacturing"] },
    ],
    toolsToLearn: ["SolidWorks", "ANSYS", "AutoCAD", "MATLAB", "Fusion 360", "Minitab (Six Sigma)", "3D Slicer"],
    topResources: [
      { name: "NPTEL: Manufacturing Processes", type: "Course" },
      { name: "Shigley's Mechanical Engineering Design", type: "Book" },
      { name: "Cengel: Thermodynamics", type: "Book" },
      { name: "GrabCAD Community", type: "Practice Platform" },
      { name: "GATE ME PYQ Analysis", type: "Practice" },
    ],
  },

  // ── CE ───────────────────────────────────────────────────────────────────────
  {
    branchId: "CE",
    branch: "Civil Engineering",
    icon: "🏗️",
    color: "amber",
    gradient: "from-amber-500 to-red-500",
    tagline: "Design the infrastructure that shapes civilizations",
    overview:
      "CE at SVNIT covers structural design, geotechnical, transportation, hydraulics, and construction management. Career paths include PSU jobs, construction companies, urban planning, and research.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-amber-400",
        subjects: ["Engineering Mechanics", "Engineering Drawing", "Engineering Geology", "Mathematics I & II", "Basics of Civil Engg"],
        skills: ["AutoCAD 2D drafting", "Surveying basics", "Site reading"],
        outcome: "Civil basics + technical drawing skills",
        tip: "AutoCAD proficiency is essential — practice daily on real building plans.",
      },
      {
        year: 2,
        label: "Core Civil",
        semesters: "Sem 3 & 4",
        color: "bg-amber-500",
        subjects: [
          "Solid Mechanics",
          "Fluid Mechanics",
          "Building Materials & Construction",
          "Surveying I & II",
          "Hydrology",
        ],
        skills: ["Total station operation", "Levelling", "Material testing", "STAAD basics"],
        outcome: "Field-ready with core civil knowledge",
        tip: "Material testing labs — document everything. Site visits = real learning.",
      },
      {
        year: 3,
        label: "Structural & Environmental",
        semesters: "Sem 5 & 6",
        color: "bg-orange-500",
        subjects: [
          "RCC Design",
          "Steel Structures",
          "Transportation Engineering",
          "Geotechnical Engineering",
          "Environmental Engineering",
          "Project Management",
        ],
        skills: ["STAAD Pro", "SAP2000", "AutoCAD Civil 3D", "IS code knowledge", "MS Project"],
        outcome: "Can design structures and manage construction projects",
        tip: "IS 456 (RCC) and IS 800 (Steel) — know them cold for exams and interviews.",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-red-500",
        subjects: [
          "Earthquake Engineering (elective)",
          "Bridge Engineering (elective)",
          "Green Buildings (elective)",
          "BIM (elective)",
          "B.Tech Project",
        ],
        skills: ["ETABS", "Revit/BIM", "LEED concepts", "Seismic design"],
        outcome: "PSU / Construction / Consulting ready",
        tip: "BIM (Revit) skills are the future of civil engineering — learn it early.",
      },
    ],
    careerPaths: [
      {
        id: "structural",
        title: "Structural Design Engineer",
        icon: "🏢",
        color: "bg-amber-500",
        description: "Design buildings, bridges, and infrastructure using IS codes.",
        steps: ["Master RCC/Steel design", "STAAD/ETABS proficiency", "IS codes", "Site supervision"],
        avgSalary: "₹4–15 LPA",
        topCompanies: ["L&T", "Shapoorji", "Afcons", "Stup Consultants", "Jacobs"],
      },
      {
        id: "psu-ce",
        title: "PSU / Government Engineer",
        icon: "🏛️",
        color: "bg-green-500",
        description: "NHAI, CPWD, Railways, State PWD — design national infrastructure.",
        steps: ["GATE CE preparation", "Focus: Structures, Soil, Fluid, Transport", "PSU application", "Interview"],
        avgSalary: "₹7–18 LPA",
        topCompanies: ["NHAI", "CPWD", "Railway", "RITES", "NHPC"],
      },
      {
        id: "urban",
        title: "Urban Planner / Smart Cities",
        icon: "🌆",
        color: "bg-blue-500",
        description: "Design livable cities with sustainable infrastructure and smart systems.",
        steps: ["Transportation planning", "GIS software", "Urban design", "Smart city concepts"],
        avgSalary: "₹5–15 LPA",
        topCompanies: ["DMRC", "HMDA", "McKinsey GI", "Arup", "Smart City Mission"],
      },
      {
        id: "construction",
        title: "Construction Management",
        icon: "👷",
        color: "bg-orange-500",
        description: "Manage large construction projects — cost, quality, timeline.",
        steps: ["Project management", "MS Project/Primavera", "Quantity estimation", "Contracts management"],
        avgSalary: "₹5–18 LPA",
        topCompanies: ["L&T Construction", "NCC", "Tata Projects", "Adani", "DLF"],
      },
    ],
    skillMap: [
      { category: "Structural Analysis", icon: "🏗️", priority: "Must Learn", items: ["STAAD Pro", "ETABS", "SAP2000", "ANSYS Civil"] },
      { category: "Drafting & BIM", icon: "✏️", priority: "Must Learn", items: ["AutoCAD", "AutoCAD Civil 3D", "Revit", "BIM concepts"] },
      { category: "Design Codes", icon: "📜", priority: "Must Learn", items: ["IS 456 (RCC)", "IS 800 (Steel)", "IS 1893 (Seismic)", "IS 875 (Loads)"] },
      { category: "Geotechnical", icon: "⛏️", priority: "Good to Have", items: ["PLAXIS", "GeoStudio", "Boring log interpretation"] },
      { category: "Project Management", icon: "📊", priority: "Good to Have", items: ["MS Project", "Primavera P6", "Cost estimation", "PERT/CPM"] },
      { category: "Sustainable Design", icon: "🌱", priority: "Advanced", items: ["LEED", "GRIHA", "Green building materials", "Life cycle assessment"] },
    ],
    toolsToLearn: ["AutoCAD", "STAAD Pro", "ETABS", "Revit", "MS Project", "ArcGIS", "AutoCAD Civil 3D"],
    topResources: [
      { name: "NPTEL: Strength of Materials", type: "Course" },
      { name: "Varghese: Limit State Design", type: "Book" },
      { name: "IS Code Library (BIS)", type: "Reference" },
      { name: "GATE CE PYQ Analysis", type: "Practice" },
      { name: "Terzaghi: Soil Mechanics", type: "Book" },
    ],
  },

  // ── CHE ──────────────────────────────────────────────────────────────────────
  {
    branchId: "CHE",
    branch: "Chemical Engineering",
    icon: "🧪",
    color: "teal",
    gradient: "from-teal-500 to-green-500",
    tagline: "Transform raw materials into life-changing products",
    overview:
      "CHE at SVNIT covers reaction engineering, transport phenomena, process design, and safety. Career paths include oil & gas, pharmaceuticals, polymer industries, and GATE/PSU roles.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-teal-400",
        subjects: ["Mathematics I & II", "Engineering Chemistry", "Engineering Physics", "Basic Chemical Engg"],
        skills: ["Lab safety", "Chemistry basics", "MATLAB basics"],
        outcome: "Strong chemistry and mathematics foundation",
        tip: "Chemistry labs — practice stoichiometry and titrations until perfect.",
      },
      {
        year: 2,
        label: "Core Chemical Engg",
        semesters: "Sem 3 & 4",
        color: "bg-teal-500",
        subjects: [
          "Chemical Engineering Thermodynamics",
          "Fluid Mechanics (CHE)",
          "Material & Energy Balances",
          "Heat Transfer",
          "Chemical Reaction Engineering I",
        ],
        skills: ["Aspen Plus basics", "Pipe flow calculations", "Energy balance sheets", "HYSYS"],
        outcome: "Can perform material-energy balances on any process",
        tip: "Material balance is the backbone — if stuck, always return to conservation laws.",
      },
      {
        year: 3,
        label: "Processes & Design",
        semesters: "Sem 5 & 6",
        color: "bg-green-500",
        subjects: [
          "Mass Transfer",
          "Chemical Reaction Engineering II",
          "Process Control",
          "Chemical Process Industries",
          "Separation Processes",
          "Safety & Hazard Analysis",
        ],
        skills: ["Aspen Plus advanced", "PID control", "HAZOP methodology", "Distillation design"],
        outcome: "Can design and simulate complete chemical processes",
        tip: "Aspen Plus simulation is industry standard — get certified if possible.",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-emerald-500",
        subjects: [
          "Process Plant Design",
          "Biochemical Engineering (elective)",
          "Polymer Engineering (elective)",
          "Environmental Engineering",
          "B.Tech Project",
        ],
        skills: ["Process flow diagrams (PFD)", "P&ID", "COMSOL", "Process safety management"],
        outcome: "Process industry / PSU / GATE ready",
        tip: "PSU (ONGC, IOCL, GAIL) GATE cut-offs — start prep from Sem 5.",
      },
    ],
    careerPaths: [
      {
        id: "process",
        title: "Process Engineer",
        icon: "🏭",
        color: "bg-teal-500",
        description: "Design and optimize chemical processes in refineries, petrochemical plants.",
        steps: ["Aspen Plus mastery", "PFD/P&ID reading", "Mass transfer design", "Safety certification"],
        avgSalary: "₹5–18 LPA",
        topCompanies: ["IOCL", "Reliance", "HPCL", "BPCL", "BASF"],
      },
      {
        id: "psu-che",
        title: "PSU Engineer (ONGC, IOCL)",
        icon: "🏛️",
        color: "bg-yellow-500",
        description: "Prestigious government oil & gas companies with high pay scales.",
        steps: ["GATE CH preparation", "Focus: CRE, Mass Transfer, Thermo, Fluid", "ONGC/IOCL application", "Group discussion + interview"],
        avgSalary: "₹10–20 LPA",
        topCompanies: ["ONGC", "IOCL", "GAIL", "HPCL", "BPCL"],
      },
      {
        id: "pharma",
        title: "Pharmaceutical Engineer",
        icon: "💊",
        color: "bg-blue-500",
        description: "Drug manufacturing, formulation, and regulatory compliance.",
        steps: ["GMP regulations", "Validation", "Pharma process scale-up", "FDA/WHO CGMP"],
        avgSalary: "₹5–15 LPA",
        topCompanies: ["Sun Pharma", "Cipla", "Dr. Reddy's", "Lupin", "Zydus"],
      },
      {
        id: "research",
        title: "Research & GATE",
        icon: "🔬",
        color: "bg-purple-500",
        description: "M.Tech at IITs or research roles in national labs.",
        steps: ["GATE CH (top 100)", "IIT M.Tech / IISc", "Research internship", "PhD abroad"],
        avgSalary: "₹14–25 LPA (post M.Tech)",
        topCompanies: ["IIT Bombay", "IIT Madras", "CSIR labs", "BARC", "DRDO"],
      },
    ],
    skillMap: [
      { category: "Process Simulation", icon: "🖥️", priority: "Must Learn", items: ["Aspen Plus", "HYSYS", "ChemCAD", "DWSIM (free)"] },
      { category: "Core Concepts", icon: "🧪", priority: "Must Learn", items: ["Mass/Energy Balance", "Thermodynamics", "Mass Transfer", "CRE"] },
      { category: "Safety & Environment", icon: "⚠️", priority: "Must Learn", items: ["HAZOP", "PSM", "EIA", "Process risk assessment"] },
      { category: "Process Design", icon: "📐", priority: "Good to Have", items: ["PFD", "P&ID", "Equipment sizing", "Cost estimation"] },
      { category: "Programming", icon: "⌨️", priority: "Good to Have", items: ["MATLAB", "Python (NumPy)", "Aspen scripting"] },
      { category: "Bioproccesses", icon: "🦠", priority: "Advanced", items: ["Bioreactor design", "Fermentation", "Downstream processing"] },
    ],
    toolsToLearn: ["Aspen Plus", "MATLAB", "COMSOL", "AutoCAD (P&ID)", "HYSYS", "Microsoft Excel (advanced)"],
    topResources: [
      { name: "NPTEL: Chemical Reaction Engg", type: "Course" },
      { name: "Fogler: Elements of CRE", type: "Book" },
      { name: "Perry's Chemical Engineers' Handbook", type: "Reference" },
      { name: "McCabe: Unit Operations", type: "Book" },
      { name: "GATE CH PYQ Analysis", type: "Practice" },
    ],
  },

  // ── IT ───────────────────────────────────────────────────────────────────────
  {
    branchId: "IT",
    branch: "Information Technology",
    icon: "🌐",
    color: "indigo",
    gradient: "from-indigo-500 to-purple-500",
    tagline: "Connect the world through data, networks, and intelligent systems",
    overview:
      "IT at SVNIT focuses on networking, web technologies, databases, cloud computing, and cybersecurity. Strong overlap with CSE but with emphasis on applied systems and enterprise tech.",
    studyPhases: [
      {
        year: 1,
        label: "Foundation",
        semesters: "Sem 1 & 2",
        color: "bg-indigo-400",
        subjects: ["Mathematics I & II", "Programming in C", "Digital Fundamentals", "Communication Skills"],
        skills: ["C programming", "Binary math", "Web browsing tools"],
        outcome: "Programming foundation + logical thinking",
        tip: "Build confidence in C by writing 50+ programs — loops, arrays, pointers are essential.",
      },
      {
        year: 2,
        label: "Core IT",
        semesters: "Sem 3 & 4",
        color: "bg-indigo-500",
        subjects: [
          "Data Structures",
          "Object-Oriented Programming (Java)",
          "Database Management Systems",
          "Computer Networks",
          "Operating Systems",
          "Web Technology",
        ],
        skills: ["Java OOP", "SQL + NoSQL", "HTML/CSS/JS basics", "Linux", "Git"],
        outcome: "Full junior developer capability",
        tip: "Build your first full-stack web app in Sem 4 — portfolio starts here!",
      },
      {
        year: 3,
        label: "Advanced IT Systems",
        semesters: "Sem 5 & 6",
        color: "bg-purple-500",
        subjects: [
          "Cloud Computing",
          "Information Security",
          "Software Engineering",
          "Advanced Database",
          "Machine Learning (elective)",
          "Mobile Application Development (elective)",
        ],
        skills: ["AWS/Azure", "React + Node.js", "Docker", "Network security", "REST APIs"],
        outcome: "Cloud-ready, security-aware full-stack developer",
        tip: "Get AWS Cloud Practitioner certification in Sem 5 — it's free to study and high-value.",
      },
      {
        year: 4,
        label: "Specialization & Placement",
        semesters: "Sem 7 & 8",
        color: "bg-violet-500",
        subjects: [
          "Distributed Systems",
          "Big Data Analytics (elective)",
          "DevOps (elective)",
          "Blockchain (elective)",
          "B.Tech Project",
        ],
        skills: ["System Design", "Microservices", "Kubernetes", "Data pipelines", "LLM APIs"],
        outcome: "SDE / Cloud / Security / Data Engineering ready",
        tip: "Build an end-to-end cloud-deployed project — recruiters love deployed apps.",
      },
    ],
    careerPaths: [
      {
        id: "sde-it",
        title: "Software Development Engineer",
        icon: "🖥️",
        color: "bg-indigo-500",
        description: "Build web and mobile applications at tech companies.",
        steps: ["Master DSA (LeetCode)", "Full-stack projects", "System design basics", "Interview prep"],
        avgSalary: "₹7–35 LPA",
        topCompanies: ["Google", "Microsoft", "Amazon", "Infosys", "TCS Digital"],
      },
      {
        id: "cloud-it",
        title: "Cloud / DevOps Engineer",
        icon: "☁️",
        color: "bg-blue-500",
        description: "Build and manage cloud infrastructure, CI/CD, and Kubernetes clusters.",
        steps: ["AWS/Azure certifications", "Docker + K8s", "Terraform IaC", "CI/CD pipelines"],
        avgSalary: "₹8–30 LPA",
        topCompanies: ["AWS", "Google Cloud", "Accenture", "Wipro", "Capgemini"],
      },
      {
        id: "cybersecurity",
        title: "Cybersecurity Engineer",
        icon: "🔒",
        color: "bg-red-500",
        description: "Protect systems from threats — pentesting, SOC, security architecture.",
        steps: ["CEH/OSCP certification", "Network security", "Ethical hacking", "SIEM tools"],
        avgSalary: "₹6–25 LPA",
        topCompanies: ["Palo Alto", "CrowdStrike", "Wipro Cybersecurity", "CERT-In", "Deloitte"],
      },
      {
        id: "data-it",
        title: "Data Engineer / Analyst",
        icon: "📊",
        color: "bg-green-500",
        description: "Build data pipelines, warehouses, and analytics systems.",
        steps: ["Python + SQL", "Apache Spark", "Airflow", "Data warehousing", "Tableau/Power BI"],
        avgSalary: "₹6–25 LPA",
        topCompanies: ["Flipkart", "Swiggy", "HDFC Bank Tech", "PhonePe", "Freshworks"],
      },
    ],
    skillMap: [
      { category: "Programming", icon: "⌨️", priority: "Must Learn", items: ["Java", "Python", "JavaScript", "TypeScript"] },
      { category: "Web Development", icon: "🌐", priority: "Must Learn", items: ["React", "Node.js", "HTML/CSS", "REST APIs", "GraphQL"] },
      { category: "Cloud & DevOps", icon: "☁️", priority: "Must Learn", items: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"] },
      { category: "Databases", icon: "🗄️", priority: "Must Learn", items: ["MySQL", "PostgreSQL", "MongoDB", "Redis", "Elasticsearch"] },
      { category: "Security", icon: "🔒", priority: "Good to Have", items: ["Network security", "OWASP Top 10", "Burp Suite", "Wireshark"] },
      { category: "Data & AI", icon: "🤖", priority: "Advanced", items: ["Python pandas", "ML basics", "Spark", "Airflow", "LLM APIs"] },
    ],
    toolsToLearn: ["VS Code", "Git & GitHub", "Docker", "AWS Console", "Postman", "Wireshark", "Kubernetes (kubectl)"],
    topResources: [
      { name: "AWS Free Tier + Cloud Practitioner", type: "Certification" },
      { name: "The Odin Project (Full Stack)", type: "Course" },
      { name: "CompTIA Security+ Guide", type: "Certification" },
      { name: "system-design-primer (GitHub)", type: "Reference" },
      { name: "Striver's DSA Sheet", type: "Practice" },
    ],
  },
];
